# Generated by Django 4.2.20 on 2025-04-18 04:13

from django.db import migrations

def create_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    
    # Create Free Trial Plan
    SubscriptionPlan.objects.create(
        name='FREE_TRIAL',
        price=0.00,
        social_accounts_limit=3,
        ai_caption_limit=10,
        has_analytics=True,
        has_content_calendar=True
    )
    
    # Create Starter Plan
    SubscriptionPlan.objects.create(
        name='STARTER',
        price=9.00,
        social_accounts_limit=3,
        ai_caption_limit=10,
        has_analytics=True,
        has_content_calendar=True
    )
    
    # Create Pro Plan
    SubscriptionPlan.objects.create(
        name='PRO',
        price=29.00,
        social_accounts_limit=10,
        ai_caption_limit=50,
        has_analytics=True,
        has_advanced_analytics=True,
        has_content_calendar=True,
        has_team_collaboration=True,
        team_member_limit=3,
        has_competitor_analysis=True
    )
    
    # Create Enterprise Plan
    SubscriptionPlan.objects.create(
        name='ENTERPRISE',
        price=99.00,
        social_accounts_limit=999999,  # Effectively unlimited
        ai_caption_limit=999999,  # Effectively unlimited
        has_analytics=True,
        has_advanced_analytics=True,
        has_content_calendar=True,
        has_team_collaboration=True,
        team_member_limit=999999,  # Effectively unlimited
        has_competitor_analysis=True,
        has_api_access=True,
        has_dedicated_support=True
    )

def reverse_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_models'),
    ]

    operations = [
        migrations.RunPython(create_subscription_plans, reverse_subscription_plans),
    ] 