# Generated by Django 4.2.20 on 2025-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_admin_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
