# Generated by Django 4.2.20 on 2025-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_sync_facebook_user_last_sync_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_used_trial',
            new_name='google_business_connected',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telegram_bot_token',
            new_name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_page_token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_business_category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_business_token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_tiktok',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_sync_youtube',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_company_token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tiktok_business_token_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_brand_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_brand_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_brand_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_brand_token_expiry',
        ),
        migrations.AddField(
            model_name='user',
            name='last_sync',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_page',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_page_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_company_page',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tiktok_business_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tiktok_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tiktok_profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_profile_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_channel',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_channel_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
