[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn linkly.wsgi:application --bind 0.0.0.0:8080"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.12" 