# Generated by Django 5.1.1 on 2025-05-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='socialbu_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='socialbu_password',
        ),
    ]
