[phases.setup]
aptPkgs = [
  "build-essential",
  "python3-dev",
  "libpq-dev",
  "zlib1g-dev",
  "libjpeg-dev",
  "libpng-dev",
  "libfreetype6-dev",
  "libtiff-dev",
  "libwebp-dev",
  "libopenjp2-7-dev"
]

[phases.build]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate && gunicorn socialbu.wsgi:application --bind 0.0.0.0:$PORT" 