[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "gunicorn wsgi:application --bind 0.0.0.0:8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "socialbu.settings"
PYTHONPATH = "/app" 