# Generated by Django 5.1.1 on 2025-05-17 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplatform',
            name='social_account',
            field=models.ForeignKey(blank=True, help_text="User's linked social account to use for publishing", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_platforms', to='socialaccount.socialaccount'),
        ),
    ]
