# Generated by Django 5.1.1 on 2025-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postplatform_social_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_description',
            field=models.TextField(blank=True, help_text='Description for link type posts', null=True),
        ),
    ]
