# Generated by Django 5.1.1 on 2025-05-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_link_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_description',
        ),
    ]
