# Generated by Django 4.2.20 on 2025-04-27 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hashtaggroup',
            name='hashtags',
            field=models.ManyToManyField(related_name='groups', to='content.hashtag'),
        ),
        migrations.AddField(
            model_name='hashtaggroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hashtaggroup',
            unique_together={('user', 'name')},
        ),
    ]
