# Generated by Django 4.2.20 on 2025-04-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='besttimetopost',
            name='platform_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_times', to='platforms.platformaccount'),
        ),
    ]
