# Generated by Django 4.2.20 on 2025-04-27 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforms', '0001_initial'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='besttimetopost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audienceinsight',
            name='platform_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_insights', to='platforms.platformaccount'),
        ),
        migrations.AddField(
            model_name='accountmetrics',
            name='platform_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='platforms.platformaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='besttimetopost',
            unique_together={('platform_account', 'day_of_week', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='audienceinsight',
            unique_together={('platform_account', 'date', 'age_range', 'gender', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='accountmetrics',
            unique_together={('platform_account', 'date')},
        ),
    ]
