# Generated by Django 5.1.1 on 2025-05-18 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='ENABLED', max_length=20)),
                ('type', models.CharField(choices=[('SEARCH', 'Search'), ('DISPLAY', 'Display'), ('VIDEO', 'Video'), ('SHOPPING', 'Shopping')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='ENABLED', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('final_url', models.URLField()),
                ('status', models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='ENABLED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='google_ads.adgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='google_ads.campaign'),
        ),
        migrations.CreateModel(
            name='GoogleAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=512)),
                ('access_token', models.CharField(max_length=512)),
                ('token_expiry', models.DateTimeField()),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('PHRASE', 'Phrase'), ('BROAD', 'Broad')], max_length=20)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_metrics', to='google_ads.adgroup')),
            ],
            options={
                'ordering': ['-date', '-impressions'],
                'unique_together': {('ad_group', 'keyword', 'match_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='google_ads.campaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
