# Generated by Django 4.2.20 on 2025-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiquota',
            options={'verbose_name': 'API Quota', 'verbose_name_plural': 'API Quotas'},
        ),
        migrations.AlterModelOptions(
            name='apiusagelog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'API Usage Log', 'verbose_name_plural': 'API Usage Logs'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['created_at'], 'verbose_name': 'Post Media', 'verbose_name_plural': 'Post Media'},
        ),
        migrations.AlterModelOptions(
            name='scheduledpost',
            options={'ordering': ['-scheduled_time'], 'verbose_name': 'Scheduled Post', 'verbose_name_plural': 'Scheduled Posts'},
        ),
        migrations.RemoveIndex(
            model_name='apiusagelog',
            name='socials_api_user_id_9976a3_idx',
        ),
    ]
