# Generated by Django 4.2.20 on 2025-04-27 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialbu_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatformconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialbutoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socialbu_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialplatformconnection',
            unique_together={('user', 'platform', 'account_id')},
        ),
    ]
