# Generated by Django 4.2.20 on 2025-04-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialbu_proxy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialbutoken',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialbutoken',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialbutoken',
            name='socialbu_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialbutoken',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialbutoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
