# Generated by Django 4.2.20 on 2025-05-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialbu_proxy', '0003_socialbutoken_email_socialbutoken_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialbutoken',
            name='access_token',
            field=models.CharField(max_length=455),
        ),
        migrations.AlterField(
            model_name='socialbutoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=455),
        ),
    ]
